### ISSUE TITLE
Unit Tests randomly fail

### ISSUE THREAD

**Issue by bobbyangers** [dj-nitehawk/FastEndpoints#10]
Hi,

I am some issue with this module.   It seems that when calling 
 app.UseFastEndpoints(); 

Tests are randomly failing with Error:
``The server has not been started or no web application was configured.``

Culprit:
[Task.Run(async () => ](https://github.com/dj-nitehawk/FastEndpoints/blob/dcdad6631acd95ac0c7763a47ed2c2fa82952065/Src/Library/Extensions/MainExtensions.cs#L118)
It seems that after 1 minute this static variables (**discoveredEndpointDefinitions**) gets set to null

I know that I am using **Specflow**/**xUnit** and that a the WebApplicaitonFactory is created for every scenario;  I tried disabling the parallelism, but tests run too slow.

Why is the code doing that ?   And could we make it configurable or be able to disable that behavior ?

**Comment by dj-nitehawk** [comment]
I don't think it's due to the static variable "discoveredEndpointDefinitions" being cleared after 1 minute. because the content of that variable is not needed after the initial endpoint discovery/registration. I clear it after 1 minute because memory profiling showed it was holding onto memory that's not needed after app startup. 

if you run the integration test project below in parallel you can see that it works without issue. https://github.com/dj-nitehawk/FastEndpoints/tree/main/Test

if you can show me how to replicate the issue with mstest, I can look into it. as I have no experience in xunit or specflow.

maybe it's running into port exhaustion/conflict or something if a webapplication is being created for each n every test case. try sharing a single webapplication per every test class maybe.

**Comment by dj-nitehawk** [comment]
we can however test your theory. I will publish a beta version of that code removed in a few hours. use that I'm your test project and see if problem gets resolved. even though I doubt it will. let's see...

**Comment by bobbyangers** [comment]
ok, let me know....

At this point, if I comment out  ``app.UseFastEndpoints();``  all works fine; and was for a couple of years....

I have to say, that the project is in transition, using both classic ``Controller`` and ``FastEndpoints``.  My goal is to transition to ``FastEndpoints``

As a side note;  the ``Microsoft.AspNetCore.Mvc.Testing`` was designed first with xUnit;   and the recommended use is to create an instance for each test to ensure "independence" between tests.  The issue is that xUnit produces a ``ITestOutputHelper`` for each test, I need to capture that helper to produce the proper output and ``.ConfigureLogging(b =>``

NOTE: 
in a "simple" project with 6 or 8 tests; it might seem ok to create a static instance server;   but global static variables are almost always a bad idea when things start to be reasonably complex.

**Comment by dj-nitehawk** [comment]
give [v2.10.1-beta1](https://www.nuget.org/packages/FastEndpoints/2.10.1-beta1) a try.

**Comment by bobbyangers** [comment]
hi @dj-nitehawk,

You are correct about that it's not the ``Task.Run()``

I did, the only to make it work is to disable parallelism.
127 tests run under 50s;  so for now it's ok.

So you can abandon this trial.

**Comment by dj-nitehawk** [comment]
what's taking the most time per test? spinning up the in memory kestral server per test, i believe.
you might be able to improve speed by sharing the factory (with a class/collection fixture) and creating httpclient per test approach. 
i don't really see the point in newing up a factory per test. in a real world situation there would only ever be 1 single kestral server listening on a single port on a server right? so why test something that's never going to happen. at least that's my line of thinking.

**Comment by bobbyangers** [comment]
For one, in your test fixture, you might want to inject different mocks (or NSubstitutes) depending on the tests via the ``ConfigureTestsServices``.

**Comment by dj-nitehawk** [comment]
right yeah...
i'll keep thinking for a way to get rid of that static variable anyway.
need to figure out how to do that without having to do assembly scanning more than once 🤔
maybe if we use a lock around the static variable might work?

**Comment by bobbyangers** [comment]
Of course I do agree that in production, this would only occur once at startup....

**Comment by bobbyangers** [comment]
Maybe you can do this if absolutely required in the 
``IHostApplicationLifetime.ApplicationStarted`` event

**Comment by dj-nitehawk** [comment]
btw, the error you mentioned seems to be thrown by a [TestHost](https://github.com/dotnet/aspnetcore/blob/5b742abe2fad7e19bb4ace67ef5fd5d20cff0dd3/src/Hosting/TestHost/src/TestServer.cs#L142). i can't find this text anywhere in the `WebApplicationFactory` source code. afaik the TestHost is an older approach to intergration testing right? with .net 6.0 we're supposed to use `WebApplicationFactory`. 

maybe this whole problem is caused by an incompatibility in a TestHost somewhere in your project?

**Comment by dj-nitehawk** [comment]
could you pls give `v2.11` a try with your setup. it might solve you problem if contetion was the actual cause.
if not, you may still wanna look into temporarily disabling old `TestHost`s and running just WAF.

**Comment by bobbyangers** [comment]
Ok I'll try ``v2.11``;
Yes this is throw by the ``TestHost`` which is used by ``WAF``...  
When calling ``CreateClient`` (on the ``WAF``) it's like the application never got created... or did not have time to finish creating.

This article from Andrew Lock :  [Supporting integration tests with WebApplicationFactory in .NET 6](https://andrewlock.net/exploring-dotnet-6-part-6-supporting-integration-tests-with-webapplicationfactory-in-dotnet-6/)
