### ISSUE TITLE
Http Request with content type `Application/Json` but no actual request body makes System.Text.Json throw exception

### ISSUE THREAD

**Issue by EthemAcar-Dev** [dj-nitehawk/FastEndpoints#124]
```
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
    WebRequest wr = WebRequest.Create($"http://localhost:3000/api/endpoint");
    wr.Method = "GET";
    wr.ContentType = "application/json";
    var response = wr.GetResponse;
```

Throws exception, i found the reason looking at the source code. 
BindToModel method of Endpoint class does the following:

```
if (isPlainTextRequest)
{
  req = await BindPlainTextBody(ctx.Request.Body);
}
else if (ctx.Request.HasJsonContentType())
{
  req = (TRequest?)await FastEndpoints.Config.ReqDeserializerFunc(ctx.Request, tRequest, serializerCtx, cancellation);
  if (req is null) throw new InvalidOperationException("JSON deserialization failed!");
}
else
{
  req = new();
}
```

isPlainTextRequest is false because ContentType is set.
ctx.Request.HasJsonContentType() returns true because ContentType is set to 'application/json'.

But we don't have any body in our request so the following line gets confused.

```
req = (TRequest?)await FastEndpoints.Config.ReqDeserializerFunc(ctx.Request, tRequest, serializerCtx, cancellation);
```
After this line of code the request never reaches the endpoint.

My hotfix was adding try-catch:

```
       try
        {
            if (isPlainTextRequest)
            {
                req = await BindPlainTextBody(ctx.Request.Body);
            }
            else if (ctx.Request.HasJsonContentType())
            {
                req = (TRequest?)await FastEndpoints.Config.ReqDeserializerFunc(ctx.Request, tRequest, serializerCtx,
                    cancellation);
                if (req is null) throw new InvalidOperationException("JSON deserialization failed!");
            }
            else
            {
                req = new();
            }
        }
        catch
        {
            req = new();
        }
```

But a better solution could be coded, when a third party developer just adds 
```
    wr.ContentType = "application/json";
```
to every call they make to fastendpoint api, it shouldn't break the api in my opinion.

I'm open to questions about this topic.

**Comment by dj-nitehawk** [comment]
we've come across this before on discord: https://discord.com/channels/933662816458645504/968858009520451595
the try/catch would certainly work but first i need to measure the performance impact of doing that since this is the hottest path in the library. if the perf drop is neglibible, i will implement it. if not, we need to figure out an alternative solution.

also fyi @fretje

**Comment by EthemAcar-Dev** [comment]
Would the following be better?:

```
 TRequest? req = default;

        if (isPlainTextRequest)
        {
            req = await BindPlainTextBody(ctx.Request.Body);
        }
        else if (ctx.Request.HasJsonContentType())
        {
            var bodyHasData = await BodyHasData(ctx.Request.Body);
            if (bodyHasData)
            {
                req = (TRequest?)await FastEndpoints.Config.ReqDeserializerFunc(ctx.Request, tRequest,
                    serializerCtx,
                    cancellation);
                if (req is null) throw new InvalidOperationException("JSON deserialization failed!");
            }
            else
            {
                req = new();
            }
        }
        else
        {
            req = new();
        }

```

```
    private static async Task<bool> BodyHasData(Stream body)
    {
        using var streamReader = new StreamReader(body);
        var content = await streamReader.ReadToEndAsync();
        return content.Length > 0;
    }

```

**Comment by EthemAcar-Dev** [comment]
We could even do this so it does not streamread twice if its plaintext:

```
 TRequest? req = default;
        var bodyContent = await BodyContent(ctx.Request.Body);
        var bodyHasData = bodyContent.Length > 0;
        if (isPlainTextRequest && bodyHasData)
        {
            req = await BindPlainTextBody(bodyContent);
        }
        else if (ctx.Request.HasJsonContentType() && bodyHasData)
        {
            req = (TRequest?)await FastEndpoints.Config.ReqDeserializerFunc(ctx.Request, tRequest,
                serializerCtx,
                cancellation);
            if (req is null) throw new InvalidOperationException("JSON deserialization failed!");
        }
        else
        {
            req = new();
        }
```
```
  private static async Task<TRequest> BindPlainTextBody(string bodyContent)
    {
        var req = (IPlainTextRequest)new TRequest();
        req.Content = bodyContent;
        return (TRequest)req;
    }

    private static async Task<string> BodyContent(Stream body)
    {
        using var streamReader = new StreamReader(body);
        return await streamReader.ReadToEndAsync();
    }
```

**Comment by dj-nitehawk** [comment]
these won't work without [ctx.Request.Body.EnableBuffering()](https://devblogs.microsoft.com/dotnet/re-reading-asp-net-core-request-bodies-with-enablebuffering/) which has a considerable perf impact since each request to the system is going to get fully buffered either in memory or disk.

in any case, need to pit each solution against eachother and benchmark before we can select a path to take.

give me a few days to try and benchmark these.

**Comment by EthemAcar-Dev** [comment]
Yeah totally forgot that. My fix would be to use the bodyContent to make a new stream so no need for (ctx.Request.Body.EnableBuffering()):

File: Endpoint.Static.cs, Line 17
```
	TRequest? req = default;
        var bodyContent = await BodyContent(ctx.Request.Body); // Get stream as string
        var bodyHasData = bodyContent.Length > 0;
        if (isPlainTextRequest && bodyHasData)
        {
            req = await BindPlainTextBody(bodyContent);
        }
        else if (ctx.Request.HasJsonContentType() && bodyHasData)
        {
            MemoryStream stream = new(Encoding.ASCII.GetBytes(bodyContent)); // String back to stream because we need the content to json deserialize.

            req = (TRequest?)await FastEndpoints.Config.ReqDeserializerFunc(stream, tRequest,
                serializerCtx,
                cancellation);
            if (req is null) throw new InvalidOperationException("JSON deserialization failed!");
        }
        else
        {
            req = new();
        }
```

File: Config.json, Line: 31
```		

	// Using Stream instead of HttpContext.Body
	internal static Func<Stream, Type, JsonSerializerContext?, CancellationToken, ValueTask<object?>>
        ReqDeserializerFunc { get; private set; }
        = (stream, tReqDto, jCtx, cancellation) =>
        {
            return jCtx == null
                ? JsonSerializer.DeserializeAsync(stream, tReqDto, SerializerOpts, cancellation)
                : JsonSerializer.DeserializeAsync(stream, tReqDto, jCtx, cancellation);
        };
```

File: Config.json, Line: 154
```
		public Func<Stream, Type, JsonSerializerContext?, CancellationToken, ValueTask<object?>> RequestDeserializer
		{
			set => ReqDeserializerFunc = value;
		}
```

I'm out of ideas for now 😄 I really wonder what your test results will be.

**Comment by dj-nitehawk** [comment]
that doesn't look any more performant than a simple try/catch imho. i see some additional allocations that need to happen which will add to gc pressure which would in turn reduce requests per second of the system. let's see...

**Comment by dj-nitehawk** [comment]
looks like my assumption was correct. it takes twice as long for the `try/catch` version to complete the operation and allocates more memory as well.

here's the benchmark project if you wanna run it yourself and see: [FETryCatchBench.zip](https://github.com/dj-nitehawk/FastEndpoints/files/8749858/FETryCatchBench.zip)

``` ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
AMD Ryzen 7 3700X, 1 CPU, 16 logical and 8 physical cores
.NET SDK=6.0.300
  [Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
  Job-SFFKRT : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT

InvocationCount=10000  IterationCount=10  LaunchCount=1  
WarmupCount=1  

```
|          Method |     Mean | Ratio |  Gen 0 |  Gen 1 | Allocated |
|---------------- |---------:|------:|-------:|-------:|----------:|
| WithoutTryCatch | 32.68 μs |  1.00 | 1.5000 |      - |     13 KB |
|    WithTryCatch | 74.13 μs |  2.27 | 2.0000 | 0.1000 |     16 KB |

so we will definitely not be adding a try/catch to the most critical & hottest execution path in fastendpoints.

you have three options the way i see it.

1. get your client applications to do the correct thing and ensure that whenever they're sending `application/json` content-type, they need to at least send an empty json object `{}` in the request body.

2. if you have no control over the client code, then you'll have to pay the performance panelty by using a custom request deserializer function like this:
```csharp
app.UseFastEndpoints(c =>
{
    c.RequestDeserializer = async (req, tDto, jCtx, ct) =>
    {
        try
        {
            if (jCtx == null)
                return await JsonSerializer.DeserializeAsync(req.Body, tDto, options: null, ct);
            else
                return await JsonSerializer.DeserializeAsync(req.Body, tDto, jCtx, ct);
        }
        catch (JsonException x)
        {
            if (x.Message.StartsWith("The input does not contain any JSON tokens"))
                return new EmptyRequest();
            throw;
        }
    };
});
app.Run();
```

3. make a feature request with the `system.text.json` team so that we can set a serializer option where we get to instruct the serializer not to throw an exception in case the supplied stream has no data.

**Comment by andtii** [comment]
This also happens if you accidentally send a get request with Content-Type

bombardier https://localhost:7035/faster/weather --method GET -n 1 -c 1 -l --header "Content-Type: application/json"

**Comment by dj-nitehawk** [comment]
@andtii get requests with a json body is supported in fastendpoints. the root cause is really a shortcoming in `system.text.json`
in order to work around that, we'll have to do a try/catch as mentioned above which reduced performance by 50%. so we will not do it. you are left with the 3 options i've mentioned above :-)

**Comment by dj-nitehawk** [comment]
we have a simple solution to this issue thanks to #148 
but your request dto must be of type `EmptyRequest`
which is basically what `EndpointWithoutRequest` is

**Comment by EthemAcar-Dev** [comment]
> we have a simple solution to this issue thanks to #148 but your request dto must be of type `EmptyRequest` which is basically what `EndpointWithoutRequest` is
> 
> fix available after `v4.3.0-beta11`

Wow amazingly simple solution, all my complex useless tries looks so dumb 🤣

**Comment by iglak** [comment]
What would be the correct solution in this case?
I currently have an endpoint like:
`/items/{id}`
And a request model:
```cs
class Request
{
    public int Id { get; set; }
}
```
Should I refactor it to an endpoint without a request and retrieve the id using Route<int>("Id")?
Or is there another recommended approach?

**Comment by matteocontrini** [comment]
> looks like my assumption was correct. it takes twice as long for the `try/catch` version to complete the operation and allocates more memory as well.
>
> here's the benchmark project if you wanna run it yourself and see: [FETryCatchBench.zip](https://github.com/dj-nitehawk/FastEndpoints/files/8749858/FETryCatchBench.zip)
>
> ``` ini
> BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
> AMD Ryzen 7 3700X, 1 CPU, 16 logical and 8 physical cores
> .NET SDK=6.0.300
>   [Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
>   Job-SFFKRT : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
>
> InvocationCount=10000  IterationCount=10  LaunchCount=1  
> WarmupCount=1  
>
> ```
> |          Method |     Mean | Ratio |  Gen 0 |  Gen 1 | Allocated |
> |---------------- |---------:|------:|-------:|-------:|----------:|
> | WithoutTryCatch | 32.68 μs |  1.00 | 1.5000 |      - |     13 KB |
> |    WithTryCatch | 74.13 μs |  2.27 | 2.0000 | 0.1000 |     16 KB |
>
> so we will definitely not be adding a try/catch to the most critical & hottest execution path in fastendpoints.



I've came across this issue and run the benchmark. I think there's a mistake since it's comparing a valid body (no exception) with an invalid one, which obviously has overhead because of the exception.

I tweaked the benchmark project, upgraded FastEndpoints, upgraded to .NET 10 and tested again.

With a request body of `{}` (valid), the try/catch adds no overhead:

| Method                         | Mean     | Error     | StdDev    | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|------------------------------- |---------:|----------:|----------:|------:|--------:|-------:|----------:|------------:|
| WithoutTryCatch_ValidEmptyJson | 8.407 us | 0.1291 us | 0.2011 us |  1.00 |    0.03 | 1.2817 |  10.76 KB |        1.00 |
| WithTryCatch_ValidEmptyJson    | 8.249 us | 0.1575 us | 0.1934 us |  0.98 |    0.03 | 1.2817 |  10.76 KB |        1.00 |

With an invalid request body (empty string), the try/catch does not add any overhead either:

| Method                           | Mean     | Error     | StdDev    | Median   | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|--------------------------------- |---------:|----------:|----------:|---------:|------:|--------:|-------:|----------:|------------:|
| WithoutTryCatch_InvalidEmptyJson | 8.505 us | 0.1752 us | 0.4971 us | 8.340 us |  1.00 |    0.08 | 1.2207 |  10.31 KB |        1.00 |
| WithTryCatch_InvalidEmptyJson    | 8.385 us | 0.1668 us | 0.2444 us | 8.436 us |  0.99 |    0.06 | 1.2207 |  10.31 KB |        1.00 |

I think this decision should be revisited. What do you think @dj-nitehawk?

[FETryCatchBench.zip](https://github.com/user-attachments/files/28150888/FETryCatchBench.zip)

**Comment by dj-nitehawk** [comment]
@matteocontrini 
i don't think we need to change the core handling in the FE hot path.
just use a middleware to correct the root cause if you're affected by this as mentioned here: https://github.com/FastEndpoints/FastEndpoints/issues/902#issuecomment-2693869128
