### ISSUE TITLE
Guidance on Error response

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#19]
Hi,

What I used to do for error responses is use the `Microsoft.AspNetCore.Mvc.ProblemDetails` standard class (https://tools.ietf.org/html/rfc7807) to wrap the errors.

I understand that there isn't any hook at the moment in FastEndpoints itself to  change the style of error responses. So best thing to do is use the standard middleware to "convert" the errors then? Or would it be a future feature to have a kind of global hook to catch the error responses? The IPostProcessor or AfterHandle are not called if you end the request in the PreProcess for example. So it seems that the standard middleware is the only option?

**Comment by dj-nitehawk** [comment]
check out `v2.21.0-beta4`
config has now been moved to it's own class with the ability to specify a func for building the error response. that should do the trick. you can return any serializable object from the func and it will be sent instead of the default error response.
https://github.com/dj-nitehawk/FastEndpoints/blob/983eb4328f16c8c89b7fa16a7c1b6369a7997a0e/Web/Program.cs#L24-L29

**Comment by stefandevo** [comment]
Very cool! Thanks.
Not sure if I am asking to much :-) but would it also be possible to change the content type in such cases as well?
According to the referred rfc, you should return `context.Response.ContentType = "application/problem+json";`
If it's too much work to change all of that, it's ok :-)

**Comment by dj-nitehawk** [comment]
fixed in beta6 release.

> Not sure if I am asking to much

definitely not. these are great improvements that i've overlooked ;-)
