### ISSUE TITLE
EndPoint registrations fails with default version

### ISSUE THREAD

**Issue by stefandevo** [dj-nitehawk/FastEndpoints#34]
In the web sample:

```
    config.VersioningOptions = o =>
    {
        o.Prefix = "v";
        o.DefaultVersion = 1;
        //o.SuffixedVersion = false;
    };
```

will cause

```
fail: FastEndpoints.DuplicateHandlerRegistration[0]
      The route "GET:/api/customer/list/recent/v1" has 2 endpoints registered to handle requests!
fail: FastEndpoints.DuplicateHandlerRegistration[0]
      The route "POST:/api/admin/login/v1" has 2 endpoints registered to handle requests!
fail: FastEndpoints.DuplicateHandlerRegistration[0]
      The route "PUT:/api/admin/login/v1" has 2 endpoints registered to handle requests!
fail: FastEndpoints.DuplicateHandlerRegistration[0]
      The route "PATCH:/api/admin/login/v1" has 2 endpoints registered to handle requests!

```

upon startup.

**Comment by dj-nitehawk** [comment]
this is actually not a bug and is due to user mistake.
atm there are 2 versions of the endpoint
```
Customers.List.Recent.Endpoint [initial version]
Customers.List.Recent.Endpoint_V1 [set to Version(1)]
```
and config doesn't define a default version.

so if you later decide to turn on default version while there are more than 1 version of an endpoint, you will obviously run in to this issue. 

the solution is to increase the version of Customers.List.Recent.Endpoint_V1 to Version(2). or turn default version off.

that is why the fail log msg exists to warn of something like this happens.

we can however change it so that the app should not be allowed to start if duplicate routes are present.

what do you think? should we log the fail msg and throw an invalid operation exception as well?

**Comment by stefandevo** [comment]
Okay; to be honest did not look to the endpoint configuration; came up with try to check what caused my other issues (see other issues). 

You are right; did not see that there was en Endpoint with no version, and then an endpoint with Version(1). 

So it's ok.

**Comment by dj-nitehawk** [comment]
i feel like the app should not be allowed to start if there's a critical misconfiguration such as this.

**Comment by stefandevo** [comment]
Correct
