### ISSUE TITLE
Dependency Injection With Validation

### ISSUE THREAD

**Issue by TheMadKow** [dj-nitehawk/FastEndpoints#44]
Question - 
How does one add dependency inside validation ?

For example, I want to pass the global configuration to the validation

```
    public class CreateItemValidator : Validator<CreateItemRequest>
    {
        public IConfig config { get; set; } < -- Approach 1

        public CreateItemValidator(IConfig config) < -- Approach 2
        {

               IConfig config = TryResolve<IConfig> < -- Approach 3

```

Non of the above approached worked for me on 3.7.0

Thanks :D

**Comment by dj-nitehawk** [comment]
as mentioned in the docs, validators are registered in the ioc container as singletons for performance reasons. so if one must access dependencies you gotta do it via `Resolve<T>()` or `TryResolve<T>()` methods. the latter part there needs to be added to the doc page which I've seemed to forgotten 😬 

btw, the decision to make the validators singletons was done after extensive benchmarking and profiling. so we will have to make due with service locator pattern there until fluentvalidation performance becomes better. 

alternatively I could make it a user configurable setting if they'd like to pay that validator instantiation panalty per request.

**Comment by dj-nitehawk** [comment]
wait... you already tried tryresolve? I will check and get back to you soon...

**Comment by dj-nitehawk** [comment]
just added support for constructor injection for validators with `v3.7.1-beta2`.
you need to enable it in the endpoint `Configure()` method via `ScopedValidator()` call, otherwise it will be registered as singleton by default.

you can see it working here:
https://github.com/dj-nitehawk/FastEndpoints/blob/3ca143caef0bc5c5aa0df3f6d0e076e78375cc64/Web/%5BFeatures%5D/Admin/Login/Models.cs#L31-L37

and here: 
https://github.com/dj-nitehawk/FastEndpoints/blob/3ca143caef0bc5c5aa0df3f6d0e076e78375cc64/Web/%5BFeatures%5D/Admin/Login/Endpoint.cs#L18
