### ISSUE TITLE
FastEndpoints was unable to find any endpoint declarations!

### ISSUE THREAD

**Issue by super-jb** [dj-nitehawk/FastEndpoints#45]
Following the instructions in the [official documentation](https://fast-endpoints.com/wiki/Get-Started.html) and when I run my solution, getting the following exception when the project loads: "FastEndpoints was unable to find any endpoint declarations!"

* Visual Studio 2022 (64 bit) / v17.0.5
* FastEndpoints v3.7.0

![image](https://user-images.githubusercontent.com/6843604/155809313-380f7d62-7b8d-49d9-ae75-6a70596d97e9.png)

**Comment by dj-nitehawk** [comment]
have you added the endpoint class declaration yet?
this error is thrown only when assembly scanning failed to discover any endpoint classes.
what does your endpoint class look like?

**Comment by super-jb** [comment]
@dj-nitehawk, yes, I've included Endpoint, Request & Response entities, copy-pasted from the documentation:
![image](https://user-images.githubusercontent.com/6843604/155810559-44f53017-3577-4363-9af7-84f708d3de4a.png)

**Comment by dj-nitehawk** [comment]
can you try the attached sample project and report back pls?
[Test-Project.zip](https://github.com/dj-nitehawk/FastEndpoints/files/8145214/Test-Project.zip)

**Comment by dj-nitehawk** [comment]
ah i see what's happening. you're using an illegal namespace :-)
the assembly scanner ignores everything that has a namespace `FastEndpoints.`
change the namespace to something else and it should be all good...

**Comment by super-jb** [comment]
Aaaa haaaaaa! That's the issue! Changed the solution + project name and volia!
Thank you so much for your help

**Comment by hamaronooo** [comment]
@dj-nitehawk I spent half an hour trying to figure out what the problem was until I found this issue. Named the project `FastEndpointsTest`. Very strange behavior. 😔

**Comment by dj-nitehawk** [comment]
there's a bunch of namespaces that's ignored by the assembly scanner because it was assumed there'd be no endpoints present in these assemblies in order to save a few milliseconds at startup.
https://github.com/FastEndpoints/FastEndpoints/blob/131b6c5066681f4cd4ed28f278455fca8d7761eb/Src/Library/Main/EndpointData.cs#L37-L53

**Comment by SergeyElishaev** [comment]
This list of "restricted" endpoints is nice, and I guess there is a reason to have it.
But it sounds like a bad idea to restrict anything that starts with it...
Because it's very obvious that someone who wants to learn and try FastEndpoints will call their project something like "FastEndpointsTest".

So changing the condition to use Equals will make much more sense here.

**Comment by dj-nitehawk** [comment]
@SergeyElishaev maintaining a full list of namespaces to be checked against with equality is not a path we wanna go down.
besides, the behavior and the workaround is documented on the first page:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/ec9f8483-a9df-409b-8b0c-b69234ba66dc)
