### ISSUE TITLE
custom unhandled exception handler

### ISSUE THREAD

**Issue by zhixXiang** [dj-nitehawk/FastEndpoints#46]
how can i custom the unhandled exception response?

**Comment by dj-nitehawk** [comment]
you can write your own exception handler middleware and register it in the pipeline instead of `app.UseDefaultExceptionHandler()`

have a look at the [source code](https://github.com/dj-nitehawk/FastEndpoints/blob/main/Src/Library/Extensions/ExceptionHandlerExtensions.cs) of the built-in handler to get idea.

**Comment by zhixXiang** [comment]
Thank you very much
This is what I need!
