### ISSUE TITLE
Support Records for Request/Response

### ISSUE THREAD

**Issue by jvetter713** [dj-nitehawk/FastEndpoints#49]
How hard would it be to support C# Records for Request and Response objects?

**Comment by sekulicb** [comment]
Just to be clear, Request/Response cannot be Records right now, but domain objects can right?

**Comment by dj-nitehawk** [comment]
@sekulicb that is correct

**Comment by VanessaRussell** [comment]
I saw this issue while attempting to find a different one and am surprised. My natural instinct is to use records for all of my models. The following dummy code seems to work as expected, so the code base already seems to support records.

Is there a particular use case that is not supported?
``` csharp
public sealed record HelloWorldRequest
{
    public string? Name { get; init; }
}

public sealed class HelloWorldRequestValidator : Validator<HelloWorldRequest>
{
    public HelloWorldRequestValidator()
    {
        _ = RuleFor(x => x.Name).NotEmpty();
    }
}

public sealed record HelloWorldResponse
{
    public string Rawr { get; init; } = "";
}

public sealed class HelloWorldEndpoint : Endpoint<HelloWorldRequest, HelloWorldResponse>
{
    public override void Configure()
    {
        Verbs(Http.GET);
        Routes("/helloworld/rawr");
        AllowAnonymous();
    }

    public override async Task HandleAsync(HelloWorldRequest request, CancellationToken cancellationToken)
    {
        if (request.Name == "rawr")
        {
            throw new NotImplementedException();
        }

        HelloWorldResponse response = new HelloWorldResponse
        {
            Rawr = $"Hello, {request.Name}",
        };

        await SendAsync(response);
    }
}
```

**Comment by dj-nitehawk** [comment]
@VanessaRussell it doesn't work if you update the route to `Routes("/helloworld/{Name}")`.
it's because the current model binding logic [does it in multiple stages](https://github.com/dj-nitehawk/FastEndpoints/blob/055eaa4d98b24e300bf3cf727539032d8998ae1f/Src/Library/Endpoint/Endpoint.Static.cs#L37-L42) working on the same instance. records won't allow mutating the request dto object in this way. we'd have to make new copies of the request at each step if we are to support records, which i believe would add to the GC pressure. long term plan is to completely rewrite the model binding system to make it more traditional.

**Comment by VanessaRussell** [comment]
@dj-nitehawk It makes sense to not fix it now if the long-term plan is to rewrite the model binding system. That said, I updated the route as you suggested in my above sample code and it still works as expected. 🤷‍♀️

![image](https://user-images.githubusercontent.com/86689712/178752407-4d3f7be7-2ed0-45dc-8ce2-846855df9a5a.png)

**Comment by dj-nitehawk** [comment]
oh yeah my bad.
it's the other form of records (without a parameterless ctor that doesn't work) such as:
```csharp
public sealed record HelloWorldRequest(string? Name);
```
so yeah feel free to use the form of records that have `init` properties and parameterless ctors.

it looks like the above became possible after we started using compiled expressions to set property values, which bypasses the type safetey/ property mutation restrictions of records. sort of an unintended bonus i guess.

i'll close this issue since we sorta support records now ;-) lol
