### ISSUE TITLE
JWT 401 unauthorized custom response

### ISSUE THREAD

**Issue by zhixXiang** [dj-nitehawk/FastEndpoints#57]
How can I respond the status 401 with message or my own error class?
Currently send only 401 without message.

**Comment by dj-nitehawk** [comment]
have a look at the "solution 1" of the following article: https://referbruv.com/blog/posts/building-custom-responses-for-unauthorized-requests-in-aspnet-core

basically when jwt auth fails, the 401 is being thrown by the authentication middleware before it reaches fastendpoints.

so, you need to register the auth middleware yourself instead of using the built-in `AddAuthenticationJWTBearer` and handle the `JwtBearerEvents` yourself and whatever you like with the response.

**Comment by zhixXiang** [comment]
Thank you, this is what I need!

**Comment by dj-nitehawk** [comment]
updated example:
```cs
var bld = WebApplication.CreateBuilder(args);
bld.Services
   .AddAuthenticationJwtBearer(
       s => s.SigningKey = "...",
       o =>
       {
           o.Events = new()
           {
               OnChallenge =
                   async ctx =>
                   {
                       ctx.HandleResponse();

                       if (ctx.AuthenticateFailure is not null)
                           await ctx.Response.SendErrorsAsync([new("Security", "You are unauthorized!")], 401);
                   }
           };
       })
   .AddAuthorization()
   .AddFastEndpoints()
   .SwaggerDocument();

var app = bld.Build();
app.UseAuthentication()
   .UseAuthorization()
   .UseFastEndpoints(
       c => c.Endpoints.Configurator =
                ep =>
                {
                    if (ep.AnonymousVerbs is null)
                        ep.Description(b => b.Produces<ProblemDetails>(401));
                })
   .UseSwaggerGen();
app.Run();
```

**Comment by ckarcz** [comment]
@dj-nitehawk is there a way to use problem details for authentication/authorization errors? i'm using an "API token" type of authentication handler.
